var ngapp = angular.module("App", ['ui.bootstrap'],
  function($interpolateProvider) {
    $interpolateProvider.startSymbol('[[');
    $interpolateProvider.endSymbol(']]');
  });

ngapp.controller("AppController", function($scope) {
  //
  // Called from the HTML file with parameters usually generated by server-side templates
  // This initiates the WS connection to the server.
  //

  $scope.initFromHTML = function(host, port, wsPort, livereloadPort) {
    $scope.host = host;
    $scope.port = port;
    $scope.wsPort = wsPort;
    $scope.livereloadPort = livereloadPort;

    var websocket = new WebSocket("ws://" + host + ":" + wsPort);
    $scope.websocket = websocket;

    websocket.onopen = function (evt) {
      $scope.$apply(
        function () {
          $scope.ws.connected(evt);
        });
    };

    websocket.onmessage = function (evt) {
      $scope.$apply(
        function () {
          $scope.ws.incomingMessage(evt);
        });
    };
  };

  $scope.ws = {
    connected:
      function (evt) {
        console.log('connected Override this in a subcontroller');
      },
    incomingMessage:
      function (evt) {
        console.log('incomingMessage Override this in a subcontroller');
      }
  };

  $scope.host = "host";
  $scope.port = "port";
  $scope.wsPort = "wsPort";

  $scope.task = {
    type:       '',
    state:      '',
    counter:    '',
    log:        '',
    started:    false
  };

  $scope.nodeList = "nodeList";
});


ngapp.controller("BodyController", function($scope) {
  $scope.isCollapsed = false;

  $scope.ws.connected = function (evt) {
    console.log('connected: ', evt);
  };

  $scope.ws.incomingMessage = function (evt) {
    console.log("incomingMessage: " + evt.data);
    var msg = JSON.parse(evt.data);
    console.log('handleServerMessage: ', msg);

    if (msg.msgType === 'task') {
      $scope.task.state = msg.taskState;
      $scope.task.counter = msg.taskCounter;
    }
    else if (msg.msgType === 'discovery') {
      $scope.nodeList = msg.nodeList;
    }
  };

  $scope.selectTask = function (taskType) {
    console.log('selectTask: ', taskType);
    $scope.task.type = taskType;
  };

  $scope.startTask = function () {
    console.log('startTask');
  };

  $scope.stopTask = function () {
    console.log('stopTask');
  };
});


